# Generated by Django 2.0.3 on 2018-04-17 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='introduce',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
