# Generated by Django 2.0.3 on 2018-04-20 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ticks', '0003_auto_20180418_1327'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finished', models.BooleanField()),
                ('create_time', models.DateTimeField()),
                ('finished_time', models.DateTimeField(null=True)),
                ('content', models.CharField(max_length=256)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ticks.Profile')),
            ],
        ),
    ]
