# Generated by Django 2.0.3 on 2018-04-20 13:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Ticks', '0004_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='finished_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
