# Generated by Django 2.0.3 on 2018-04-20 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticks', '0005_auto_20180420_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='finished_time',
            field=models.DateTimeField(null=True),
        ),
    ]
